# Generated by Django 6.0.4 on 2026-07-06 06:50

import django.core.validators
from django.db import migrations, models


def seed_reading_list(apps, schema_editor):
    Post = apps.get_model("posts", "Post")

    featured_books = [
        {
            "title": "Laskar Pelangi",
            "author": "Andrea Hirata",
            "genre": "Drama",
            "rating": 5,
            "status": "selesai",
            "year_read": 2026,
            "review": "Cerita yang hangat tentang mimpi, persahabatan, dan semangat mengejar pendidikan.",
            "favorite_quote": "Mimpi adalah kunci untuk kita menaklukkan dunia.",
            "text": "Novel inspiratif yang sangat berkesan.",
        },
        {
            "title": "Bumi Manusia",
            "author": "Pramoedya Ananta Toer",
            "genre": "Sejarah",
            "rating": 5,
            "status": "selesai",
            "year_read": 2026,
            "review": "Kuat secara karakter, sejarah, dan konflik sosial yang terasa relevan sampai sekarang.",
            "favorite_quote": "Kita telah melawan, Nak, niscaya kita akan menang.",
            "text": "Novel klasik dengan pesan sosial yang kuat.",
        },
        {
            "title": "Negeri 5 Menara",
            "author": "Ahmad Fuadi",
            "genre": "Inspirasi",
            "rating": 4,
            "status": "selesai",
            "year_read": 2026,
            "review": "Menunjukkan bahwa disiplin dan keyakinan bisa membawa kita ke tempat yang jauh.",
            "favorite_quote": "Man jadda wajada.",
            "text": "Menguatkan semangat untuk terus belajar.",
        },
        {
            "title": "Perahu Kertas",
            "author": "Dee Lestari",
            "genre": "Romansa",
            "rating": 4,
            "status": "membaca",
            "year_read": None,
            "review": "Ringan, puitis, dan cocok untuk pembaca yang suka konflik personal yang lembut.",
            "favorite_quote": "Ada yang lebih kuat dari logika, yaitu rasa.",
            "text": "Novel yang enak dibaca dan mudah diingat.",
        },
        {
            "title": "Ayat-Ayat Cinta",
            "author": "Habiburrahman El Shirazy",
            "genre": "Religi",
            "rating": 4,
            "status": "ingin",
            "year_read": None,
            "review": "Masih menjadi daftar baca wajib karena perpaduan romance, nilai moral, dan konflik batin.",
            "favorite_quote": "Cinta adalah anugerah yang harus dijaga.",
            "text": "Masuk daftar ingin dibaca ulang.",
        },
    ]

    if not Post.objects.exists():
        for book in featured_books:
            Post.objects.create(**book)
        return

    first = Post.objects.order_by("id").first()
    if first and (
        first.title == "Novel tanpa judul"
        or first.author == "Penulis belum diisi"
        or not first.review
    ):
        for field, value in featured_books[0].items():
            setattr(first, field, value)
        first.save()

    existing_titles = set(Post.objects.values_list("title", flat=True))
    for book in featured_books[1:]:
        if book["title"] not in existing_titles:
            Post.objects.create(**book)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-rating', 'title']},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Penulis belum diisi', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='favorite_quote',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default='Umum', max_length=80),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Nilai 1 sampai 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('selesai', 'Selesai dibaca'), ('membaca', 'Sedang dibaca'), ('ingin', 'Ingin dibaca')], default='selesai', max_length=12),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Novel tanpa judul', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='year_read',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(seed_reading_list, migrations.RunPython.noop),
    ]
