# Generated by Django 6.0.4 on 2026-07-06 07:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_post_owners(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    User = apps.get_model("auth", "User")

    owner = User.objects.filter(username="wahyu").first()
    if owner:
        Post.objects.filter(created_by__isnull=True).update(created_by=owner)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_post_author_post_favorite_quote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-rating', 'title'], 'verbose_name': 'Novel', 'verbose_name_plural': 'Daftar novel'},
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Penulis belum diisi', max_length=120, verbose_name='Penulis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='favorite_quote',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kutipan favorit'),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(default='Umum', max_length=80, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Nilai 1 sampai 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.TextField(blank=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('selesai', 'Selesai dibaca'), ('membaca', 'Sedang dibaca'), ('ingin', 'Ingin dibaca')], default='selesai', max_length=12, verbose_name='Status baca'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, verbose_name='Catatan singkat'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Novel tanpa judul', max_length=200, verbose_name='Judul novel'),
        ),
        migrations.AlterField(
            model_name='post',
            name='year_read',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun dibaca'),
        ),
        migrations.RunPython(assign_post_owners, migrations.RunPython.noop),
    ]
